[ids]
*
-0001:0001
abcd:0123

[main]
leftalt = layer(meta_mac)
leftmeta = layer(alt_mac)
rightalt = layer(meta_mac)
rightmeta = layer(alt_mac)
print = layer(alt_mac)
sysrq = layer(alt_mac)
capslock = overload(nav, esc)

[nav]
h = left
j = down
k = up
l = right
space = leftmouse

[nav+alt]
space = rightmouse

[meta_mac:C]
c = C-insert
v = S-insert
x = S-delete

# Text navigation (Mac-like)
left = home
right = end
up = C-home
down = C-end
backspace = macro(S-home backspace)

[alt_mac:A]
left = C-left
right = C-right
backspace = C-backspace
